# Generated by Django 5.0.6 on 2024-08-09 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField()),
                ('nickname', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TermPeriod',
            fields=[
                ('week_commencing', models.DateField(primary_key=True, serialize=False)),
                ('week_name', models.CharField(max_length=255)),
                ('period_name', models.CharField(max_length=255)),
                ('period_type', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^term_time|holiday$')])),
            ],
        ),
        migrations.CreateModel(
            name='SeatingLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classmate.class')),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classmate.floorplan')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classmate.termperiod')),
            ],
        ),
        migrations.CreateModel(
            name='SeatingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_num', models.IntegerField()),
                ('seating_layout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classmate.seatinglayout')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seating_assignments_as_partner', to='classmate.student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_assignments_as_student', to='classmate.student')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.student')),
                ('week_commencing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.termperiod')),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.job')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.student')),
                ('week_commencing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.termperiod')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmate.student')),
                ('week_commencing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_as_week_commencing', to='classmate.termperiod')),
                ('week_until', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_as_week_until', to='classmate.termperiod')),
            ],
        ),
    ]
